---
title: "Assignment 4"
subtitle: "Task 2"
author: "Marie Bouffard"
date: "3/4/2021"
output:
  html_document:
    theme: cosmo
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

# Attach Packages
library(tidyverse)
library(here)

```

For Task 2, you will find an equation with parameters estimated by nonlinear least squares for the increase in global wild fish catch from 1950 – 2012. **Hint: You will want to set 1950 = 0 (i.e., create a new column with years starting at 0, instead of value 1950, and use those values for your model…).**

For Task 2: 

a)	An exploratory graph of wild catch over time (does not need to be finalized). Include the exploratory graph in your knitted HTML. 
b)	In text below the exploratory graph: What type of relationship describes the trend? What does that look like mathematically (include an equation, possibly using LaTeX)? What are your initial estimates for the parameters in the model? 
c)	Use nonlinear least squares to find parameters for your model describing wild catch. Report the parameter outcomes (with units) in text or a table.
d)	Prepare a finalized (publication quality) graph showing both the original data and your model output. No figure caption required. The code and graphs should appear in your knitted HTML (OK to use code folding). 


***

**Data Source**
Global wild fish catch and aquaculture production, compiled by Earth Policy Institute with 1950-2010 from U.N. Food and Agriculture Organization (FAO), Global Capture Production and Global Aquaculture Production, electronic databases, at www.fao.org/fishery/topic/16140/en.