---
title: "Assignment 4"
subtitle: "Task 3"
author: "Marie Bouffard"
date: "3/4/2021"
output:
  html_document:
    theme: cosmo
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

# Attach Packages
library(tidyverse)
library(here)

```

In the study, 22 out of 36 surveyed UCSB community members (61%) identifying as nonbinary/genderqueer responded that they had personally experienced “exclusionary, offensive, hostile or intimidating conduct” (compared to 26% and 19% for those identifying as women and men, respectively). 

Your goal is to find a confidence interval for the proportion of nonbinary/genderqueer students experiencing exclusionary, hostile or intimidating experience at UCSB using bootstrapping. Create a vector reflecting the collected survey data (n = 36), then find the bootstrapped 95% confidence interval for the proportion of genderqueer individuals experiencing exclusionary conduct based on the 2014 UCSB survey data.
 
Hint: this task will require you to recreate the data and create a function that calculates the proportion of a specified outcome for each bootstrap sample. The proportions for each bootstrap sample are what will be plotted in your histogram below.
 

For Task 3:

a)	Include any code you wrote to make the original sample vector, create the “proportions function,” and find bootstrap samples (use at least 10,000 bootstrap samples here).

b)	A histogram of bootstrapped proportions (does not need to be finalized). The histogram should show up in your knitted HTML. 

c)	A final statement (in text) describing the bootstrapped CI in the context of the data (suitable for publication).

***

**Data Source**

Rankin & Associates, Consulting. (2014). Campus CLimate Projecct Final Report, University of California Santa Barbara. Available at http://campusclimate.ucop.edu/_common/files/pdf-climate/ucsb-full-report.pdf)